### PR TITLE
Support for get_transfer_by_txid Wallet-RPC method and multiple destinations amount bugfix.

### PR DESCRIPTION
**Pull request by lialsoftlab**
Added support for get_transfer_by_txid wallet-RPC method, since we can't get info for concrete transfer by txid through wallet incoming()/outgoing() calls. Also added bug fix for outgoing transfers processing with multiple destinations, since amount must be from destinations array not from transfer amount.

### CODE REVIEW

**Comment by emesik** [comment]
Hi Alexey,

Thanks for your input. Could you please cover that code with some tests? Apart from standard behavior three particular cases come to my mind as worth testing:

1. Transaction with given hash is not found.
2. Transaction exists but contains no payment related to the account/wallet.
3. Transaction contains more than a single payment related to the account/wallet.

Thanks for signalling the bug as well, I'll check it separately.

**Comment by lialsoftlab** [comment]
Hi Michał!
Ok I'll write a tests, but anyway:
1. monero.exceptions.TransactionNotFound if hash is invalid or not existent.
2. monero.exceptions.TransactionNotFound if hash for tx from some other wallet.
3. You get one transaction with amount equal to sum of individual payments.

**Comment by emesik** [comment]
The destinations bug has been fixed in d81b29182fdb9940accc9664144697e0d1fcf6ea and is present in v0.5.1

**Comment by lialsoftlab** [comment]
Ok. Thanks!

**Pull request closed without merging**
